import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { NavigationMenuDemo } from "./_components/NavigationMenuDemo";
import Script from "next/script";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          strategy="beforeInteractive"
          id="middleware-lib-init"
          src="https://cdnjs.middleware.io/browser/libs/0.0.1/middleware-rum.min.js"
          type="text/javascript"
        />
        <Script strategy="beforeInteractive" id="middleware-script-init">
          {`
                if (window.Middleware){
                    window.Middleware.track({
                    serviceName: "<SERVICE NAME>",
                    projectName: "<PROJECT NAME>",
                    accountKey: "<ACCOUNT KEY>",
                    target: "https://<UID>.middleware.io",
                    });
                }
                `}
        </Script>
      </head>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <NavigationMenuDemo />
        {children}
      </body>
    </html>
  );
}
