apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: dotnet-app
  name: dotnet-app
  namespace: default
spec:
  ports:
    - name: "Application"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: dotnet-app

---

apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.network/dotnet-demo-default: "true"
    io.kompose.service: dotnet-app
  name: dotnet-app
  namespace: default
spec:
  containers:
    - env:
        - name: MW_AGENT_SERVICE
          value: mw-service.mw-agent-ns.svc.cluster.local
        - name: MW_API_KEY
          value: your-api-key
        - name: OTEL_SERVICE_NAME
          value: dotnet-service
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: project.name=dotnet-project
      image: your-image-name:tag
      name: dotnet-app
      ports:
        - containerPort: 5000
          hostPort: 5000
          protocol: TCP
      resources: {}
  restartPolicy: OnFailure
